### ISSUE TITLE
Ability to use Headless Chrome?

### ISSUE THREAD

**Issue by atdiff** [addyosmani/webpack-lighthouse-plugin#11]
Is there a way to use headless chrome with the plugin?
If not, it'd be a nice option to have similar to how lighthouse itself allows - https://github.com/GoogleChrome/lighthouse/blob/master/docs/headless-chrome.md#cli-headless

**Comment by ev1stensberg** [comment]
I think you can use all lighthouse flags, `{ flags: ['headless']}`

**Comment by atdiff** [comment]
@ev1stensberg - Tried this and no luck:
```
new WebpackLighthousePlugin({
                url: 'http://localhost:8000',
                perf: true,
                flags: ['headless']
})
```
