### ISSUE TITLE
Additional output options

### ISSUE THREAD

**Issue by atdiff** [addyosmani/webpack-lighthouse-plugin#12]
It'd be nice to have the ability to configure options like the output format (JSON, HTML, other) and to specify the output location.
Lighthouse offers options of:
- --output
- --output-path

**Comment by ev1stensberg** [comment]
Try adding outputPath in your webpack.config, it should work!

**Comment by atdiff** [comment]
@ev1stensberg - Ran this and it didn't change the output folder:
```
new WebpackLighthousePlugin({
                url: 'http://localhost:8000',
                perf: true,
                outputPath: 'C:\\temp\\'
})
```

**Comment by ev1stensberg** [comment]
Sorry, let's group those up at #13
