### ISSUE TITLE
Lighthouse plugin causes vue-template-loader to fail to load

### ISSUE THREAD

**Issue by steveworkman** [addyosmani/webpack-lighthouse-plugin#15]
Originally raised in https://github.com/vuejs/vue-cli/issues/3394

Trying to use this plugin with the VueJS CLI causes the vue-template-loader to fail to load. The Vue team identified this as a problem with Lighthouse mocking the window object.

You can see this reproduced in https://github.com/steveworkman/vue-cli-bug-repo

Is this something that can change?

**Comment by evenstensberg** [comment]
I'll have a look but most likely this is a bug with lighthouse itself

**Comment by steveworkman** [comment]
@evenstensberg I thought so, but I wanted to raise this here first just to be sure. Lighthouse has a lot of open issues, and this is probably a problem with all VueJS CLI applications.

Temporarily, to get lighthouse working,I may be able to set this up as a separate job, but it'll lose this nice webpack integration

**Comment by evenstensberg** [comment]
I'll see what we can do. @patrickhulce might have some insight here

**Comment by steveworkman** [comment]
The repo has the bug in it. If you remove the WebpackLighthousePlugin from https://github.com/steveworkman/vue-cli-bug-repo/blob/master/vue.config.js the application runs.

The note of Lighthouse mocking the window object comes from the Vue team in here: https://github.com/vuejs/vue-cli/issues/3394 - honestly I don't know any more about this than what they've said

**Comment by patrickhulce** [comment]
I'm not denying the existence of the bug :) I'm just saying it happens before Lighthouse is invoked. 

Thanks very much for the comment link! I see now what they're saying, window object on the node side!

@evenstensberg you `require` lighthouse in on the node side? The version of LH this package is using is pretty old and there used to be polyfills to get devtools to work correctly which is probably what's going on. If you update to 4.0 it should go away.

**Comment by evenstensberg** [comment]
Fixed now, please close issue once you have verified.

**Comment by steveworkman** [comment]
Yep, that works. Thanks a lot!
