### ISSUE TITLE
Outdated link

### ISSUE THREAD

**Issue by mgifford** [addyosmani/webpack-lighthouse-plugin#16]
On https://github.com/addyosmani/webpack-lighthouse-plugin/blob/master/README.md

In this sentence:
"If you're trying to use webpack-dev-server with this plugin, first run it against your local build using the webpack-dev-server CLI:"

The link needs to get updated to: 
https://webpack.js.org/

**Comment by evenstensberg** [comment]
Fixed now, thanks for reporting!
