### ISSUE TITLE
Greater Clarity about how this might work in a CI/CD pipeline

### ISSUE THREAD

**Issue by spmcbride1201** [addyosmani/webpack-lighthouse-plugin#9]
Thanks so much for your work on web perf in general and Lighthouse in particular. The tools are super useful, and I'm hoping to figure out a way to generate Lighthouse reports in my CI environment on every build. I currently generate and archive Istanbul LCOV and Webpack Bundle Size reports in this manner. However, I'm not really clear on how this might work with this plugin. 

The README shows that I need to preconfigure the plugin with an endpoint to test. Assuming that Webpack is generating is building the production bundle that I'm serving, I'm a bit unclear about how I might locally serve this new production bundle, execute the plugin, and then tear everything down.

Am I perhaps misunderstanding the use case for this plugin? If not, do you have any suggestions about how best to achieve this?

**Comment by ev1stensberg** [comment]
Hi @spmcbride1201 ! 

Here's what I found on testing `lighthouse` in a CI, which could be used w.r.t this plugin! 

https://github.com/ebidel/lighthouse-ci
https://github.com/GoogleChrome/lighthouse/issues/1645#issuecomment-310236426

**Comment by spmcbride1201** [comment]
@ev1stensberg - Sorry for the delay getting back to you and thanks for the breadcrumbs! You can go ahead and close out this issue.

**Comment by ev1stensberg** [comment]
Gotcha! Feel free to send me an email or a message on Twitter if you got any other questions @spmcbride1201 👍
